### ISSUE TITLE
Kartik/datarangepicker not working in Backend.

### ISSUE THREAD

**Issue by flrmatjd** [trntv/yii2-starter-kit#135]
Hi

I have downloaded datarangepicker and implement to frontend. It is working. But in Backend , It doesn`t working.

I think backend javascript has some problem.

Backend`s input box `s style is different with Frontend.

Backend`s form-input box is rectangle but Frontend`s form-input box is rounded rectangle

**Comment by trntv** [comment]
can you provide console output? is there any errors?

**Comment by flrmatjd** [comment]
Uncaught TypeError: $(...).tooltip is not a function(anonymous function) @ app.min.js?v=1429175996:13jQuery.Callbacks.fire @ jquery.js?v=1429175995:3094jQuery.Callbacks.self.fireWith @ jquery.js?v=1429175995:3206jQuery.extend.ready @ jquery.js?v=1429175995:3412completed @ jquery.js?v=1429175995:3428

**Comment by flrmatjd** [comment]
Uncaught TypeError: jQuery(...).daterangepicker is not a function(anonymous function) @ index:806jQuery.Callbacks.fire @ jquery.js?v=1429175995:3094jQuery.Callbacks.self.fireWith @ jquery.js?v=1429175995:3206jQuery.extend.ready @ jquery.js?v=1429175995:3412completed @ jquery.js?v=1429175995:3428

**Comment by flrmatjd** [comment]
I think this error reason is common/assets/AdminLte and JquerySimScroll.

**Comment by trntv** [comment]
Create issue in kartik/datarangepicker, the problem in their AssetBundle, that causes jquery to be included twice.

**Comment by flrmatjd** [comment]
It works in Frontend.
But not in Backend .I think this is not daterangepicker` problem.
If this is daterangepicker `s problem then It must doesn`t work at frontend. But work in frontend

**Comment by trntv** [comment]
The problem is here:

https://github.com/kartik-v/yii2-date-range/blob/master/LanguageAsset.php#L19

and here:

https://github.com/kartik-v/yii2-date-range/blob/master/MomentAsset.php#L19

I don't know why they are forcing to use POS_HEAD, while default position in Yii is POS_END, and POS_END is a right way, scripts should be registered before closing ``body`` to decrease page load time.
But this causes that jquery registers twice, second time after daterangepicker script.

If you want to use this wigdet, you should change js position for adminlte bundle in your code, i don't want to do it by default for everybody, because it isn't right.

**Comment by trntv** [comment]
figured out. this fix should help.
