### ISSUE TITLE
In Backend: Not able to allow access on actions

### ISSUE THREAD

**Issue by mohdbashir** [trntv/yii2-starter-kit#217]
I made the module with name projects and there is a default controller in which want to allow access for specific user. Below is my code:

    namespace backend\modules\projects\controllers;
    use Yii;
    use yii\web\Controller;
    use yii\web\NotFoundHttpException;
    use yii\filters\VerbFilter;
    use yii\data\ArrayDataProvider;
    use yii\filters\AccessControl;
    class DefaultController extends Controller
    {
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [                   
                    [                    
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['administrator'],
                    ],                   
                    
                ],
            ],
             
        ];
        }
    }

But it is not working. If i comment the code 'as globalAccess' on file backend/config/web.php then it works but the 'as globalAccess' permission working stop.

How i will be able to allow permission on backend controllers.

**Comment by XzAeRo** [comment]
You have a misconception about roles and access control. You should have some like this in your behaviours.
```
'access' => [
    'class' => AccessControl::className(),
        'rules' => [                   
             [                    
                'actions' => ['index'],
                'allow' => true,
                'roles' => ['@'],
            ],                   
    ],
],
```
Where `@` will match if the user is authenticated, and `?` will match if the user is guest. `*` is a wildcard.
More about this in [here](https://github.com/yiisoft/yii2/blob/master/docs/guide/security-authorization.md#access-control-filter-).

To verify if a user is administrator, manager, or simple user, you can access that information through the RBAC user configuration.
For example, if you want to allow only administrators in the index action, you may write something like:

```
use common\models\User;

'access' => [
    'class' => AccessControl::className(),
        'rules' => [                   
             [                    
                'actions' => ['index'],
                'allow' => true,
                'roles' => ['@'],
                'matchCallback' => function ($rule, $action) {
                    return Yii::$app->user->can(User::ROLE_ADMINISTRATOR);
                }
            ],                   
    ],
],
```

The `matchCallback` function has to return `true` to validate if the user should be allowed, or `false` if it shouldn't.
The `Yii::$app->user->can()` function will return true or false if the user has the role, or a higher role privilege. Eg: if the user is admin, but I'm only verifying if the user can 'manager', the function will return `true` because `administrator` is a higher level than `manager`.

You can find about the roles and privileges in the following files:
* [console\controllers\RbacController](https://github.com/trntv/yii2-starter-kit/blob/master/console/controllers/RbacController.php)
* [common\models\User](https://github.com/trntv/yii2-starter-kit/blob/master/common/models/User.php)

And an example using the privilege check in the [frontend layout](https://github.com/trntv/yii2-starter-kit/blob/master/frontend/views/layouts/base.php#L40)

Hope this helps!
Happy coding :smile:

**Comment by mohdbashir** [comment]
Thanks for the reply.

I have updated my code as suggested by you but still not working. Below is my code

    'access' => [
                'class' => AccessControl::className(),
                'rules' => [                   
                    [
                        //'controllers'=>['default'],
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {                            
                            return Yii::$app->user->can('administrator');
                        },                        
                    ],                   
                    
                ],
            ],


 If i comment the code 'as globalAccess' on file backend/config/web.php then it works but the 'as globalAccess' permission working stop.
Please suggest.

**Comment by mohdbashir** [comment]
Can you suggest me how to resolve above issue?

**Comment by XzAeRo** [comment]
I haven't been able to replicate your issue.
I'm not sure what could be wrong, since I created a module just like the one you posted, and the access control worked without a problem. (using an "empty" project).

Tha only thing that may be causing issues, is since I didn't create an exception handler for the authentication process, the module fails in an ugly way, showing an stack trace but in plain text.

I suggest you to try to test your module in a fresh installation, an to make sure to initialize the rbac module correctly.

**Comment by mohdbashir** [comment]
Please reopen this issue.
I have not able to resolve this issue. Can you please suggest me how to write the access rule for module in file backend/config/web.php
Because i am unable to to write the rule in module itself.

**Comment by mohdbashir** [comment]
Please reopen this issue.
Today, i have installed fresh starter-kit for new project and made the test module to check permission issue for module is working or not. Still i am facing same problem.

My concern is i would like to create a new module in the backend and want to apply the access on action of module controller.

Please suggest.
