### ISSUE TITLE
Don't modify old migrations, add new ones instead!

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#222]
After pulling the latest changes into my project, I ran into problems with `Page` model. They were caused by the fact that there is new column in the `page` table so I thought migration would solve it. Instead of new migration, the old one has been modified which is bad practice:
https://github.com/trntv/yii2-starter-kit/commit/2b5ae5715dbf41c8fa804d31091162bcfc5ed2ce#diff-001c68e156ffc79e1eca0be46f9ddccc

The idea is that modifications of the schema should come with new migrations. I know that you don't officially support people using `yii2-starter-kit` to pull changes from the upstream. But still facilitating this will make more people stay with the project.

**Comment by XzAeRo** [comment]
Yes, I completely agree.
Also, a better versioning of the project could prevent this backwards compatibility problems. Things that break backwards compatibility should be in different versions (v1.x , v2.x , ...).
Maybe adopting the [Yii versioning guidelines](https://github.com/yiisoft/yii2/blob/master/docs/internals/versions.md) should be a good idea.

Probably this is a lot of work for @trntv to handle, but making pull requests could help (specially since @trntv is maintaining this project alone... maybe he needs collaborators?).

**Comment by trntv** [comment]
The main reason why i'm modifying old migrations is that starter kit isn't a ``package``, it is a ``project``. 
https://github.com/trntv/yii2-starter-kit/blob/master/composer.json#L19
It isn't updatable. If i will create a migration on every change i make to db there will be a lot of them...

But i'll try not to change them very often, at least in patch versions

> maybe he needs collaborators?

:+1:

**Comment by ddinchev** [comment]
Yes, but as the project evolves, it's absolutely acceptable, even expected, to have lots of migrations. I've been working on a project with hundreds of them. The idea behind migrations is that you can evolve the schema together with the code. And if you modify migrations, the code changes but the schema is always bound to the latest code.

**Comment by ddinchev** [comment]
@trntv this issue was meant to raise awareness regarding issues with modifying migrations, as something to be considered in future changes. Feel free to close it and take actions as you find appropriate.
