### ISSUE TITLE
Integrate RBAC Management

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#325]
It'd be cool to manage RBAC from the get-go in yii2-starter-kit.

The following plugin might be a nice addition to fresh installations: http://www.yiiframework.com/extension/yii2-rbac-plus/

**Comment by XzAeRo** [comment]
I've been using this extension in a project (using yii2-starter-kit), and it's working like a charm.
But I wouldn't bundle this extension right away in fresh installations, specially since this project is intended to be a starting point for development (small form-factors to start developing), and I believe this is a little over-complicated for a simple project.

But that is just my opinion.

**Comment by mysoundmagic** [comment]
hello, i need some help about rbac in yii2 starter kit.I use editOwnPost in action update article but i think it does not work, user who has post still forbidden.

**Comment by davidjeddy** [comment]
@XzAeRo any UI's you'd recommend for RBAC management? As RBAC is already included in the boilerplate, having an admin UI is probably a good idea.

**Comment by XzAeRo** [comment]
@davidjeddy I'm really fond of AdminLTE design in general, so I'd suggest that.

**Comment by davidjeddy** [comment]
the admin panel used AdminLTE already; someone/s would have to write a CRUD module to administer the RBAC assignments. The current rbac system is built from yii\rbac's provided abilities.

https://github.com/yii2mod/yii2-rbac may be an answer to this that already exists.

**Comment by davidjeddy** [comment]
Rebased on the new master branch. Reopening PR.

**Comment by trntv** [comment]
it already fixed in master :-)
