### ISSUE TITLE
your vagrant file has problem in window7 with virtualbox5.0 and vagrant 1.7.x

### ISSUE THREAD

**Issue by buuug7** [trntv/yii2-starter-kit#334]
this is screen show:
![image](https://cloud.githubusercontent.com/assets/12119289/11710821/047d389e-9f5d-11e5-9002-bb813274d8aa.png)

**Comment by trntv** [comment]
Sorry, i don't have windows to check this issue. I will be appreciated if someone will help to check and fix it.

**Comment by davidjeddy** [comment]
@buuug7 What are you using to a the server service?

**Comment by rowasc** [comment]
I have a windows  system (dual-boot). Will verify later tonight.
Regards
Romina

**Comment by buuug7** [comment]
are you successfull install by vagrant and tell me how to install in windows

**Comment by rowasc** [comment]
Hi, @buuug7  . 
I had some errors, but nothing like that. Now it's working.

I did not have system packages missing tho (like mysql in your screenshot), so I am not sure how I can help. 

Something to note: I am running the current stable version of Vagrant (1.7.4) for windows, but same virtualbox version as yours. If you look at the release list , there were a bunch of releases in between 1.5.x and 1.7.4, so I would probably start by deleting the old vagrant setup and reinstalling with 1.7.x. 

In another note, things that did fail, and solutions: 

* I am not sure why, but  the fxp/composer-asset-plugin failed to install. Have you had any issues like this before?  I fixed it by SSHing to the vagrant box and doing it manually, but It's something to look into (probably will try to fix it in the vagrant config after a business trip I have this week, but that will be on friday, at least ... :/ ) . 

* After that, I had to manually run the console setup because well, it had failed because deps were not installed, obviously.

* Could not access the site since there is was a symlink error for the assets. I ended up solving it by changing : 

    'components' => [
            'assetManager' => [
                'class' => 'yii\web\AssetManager',
                 'linkAssets' => false,

It was just a problem with the shared folder and symlinks, apparently (now the assets are being published just fine). Link to docs about linkAssets property: http://www.yiiframework.com/doc-2.0/yii-web-assetmanager.html#$linkAssets-detail

Sorry I could not find the issue @buuug7 , please let me know if you try with vagrant 1.7 and how it goes. 

Romina
