### ISSUE TITLE
Add CircleCI or similar to run unit tests in the project

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#362]
If there is CI, it will verify the proposed changes are not breaking anything tested. Also it will make sense to start requesting tests of new features. CircleCI, Drone, Travis are all free CI tools for open source projects. Circle is also free for one private project that makes it attractive option.

**Comment by trntv** [comment]
Yep, i know what it is and use it for some of my projects. The problem is in tests support. 
In case if Travis will be plugged in i'll spend a lot of time (re)writing tests. But i think we can try, the amount of new features is not so big as it was at the beginning.

**Comment by davidjeddy** [comment]
+1 for adding CI support (of any type). Since this project is getting to a mature state more and more higher visibility projects are/will be based on it. No tests will turn potential consumers away.

I myself use CodeShip + CodeCeption for some projects; generally happy with the solution.

Breakdown of CI/CD services: http://www.yegor256.com/2014/10/05/ten-hosted-continuous-integration-services.html
