### ISSUE TITLE
Move the user and api modules out

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#388]
The user and api modules should not be modules at all in this case. The idea of using modules is that they are decoupled and can easily be transferred to new application. But in `yii2-starter-kit` user module is coupled to many classes in the boilerplate, so imho it will be cleaner if we pull it out in `frontend/models | controllers | views`. I can do the change myself if we agree on this.

However the `api` module imho should be moved as sub-application `api/`, just like `backend/` and `frontend/`. As it probably won't have any coupling to `frontend/` and could be deployed on `api.example.com` lets say.

Again - I can make a PR with the changes if we agree @trntv

**Comment by trntv** [comment]
The idea with those modules was to store their code separately from other application because many applications don't need user management or rest api at all.

And yes, I separate REST API in all my applications in a seprate sub-application on `api.*` subdomain. So you can create a PR for this or i'll made it myself.

**Comment by desaikalpesh34** [comment]
check [https://github.com/desaikalpesh34/yii2-kit](https://github.com/desaikalpesh34/yii2-kit) i have tried little bit to accomplish this..
