### ISSUE TITLE
File Image Upload Vulnerability

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#426]
I did some tests with the image upload for the profile and I was able to upload some php with malicious code.

Although the file functionality seems to stop uploading files other than images into the web server, these files are stored in the web server independently as they passed the filters. I found that the table “file_storage_time” stores the file reference locations that independently passed the image filters installed in the web application. The following picture shows the entry item in the table with the reference location to the malicious files that I attempted to upload - https://www.dropbox.com/s/slfe168az9mkv5o/Screenshot%202016-05-28%2018.30.55.png?dl=0

**Comment by XzAeRo** [comment]
Well, to be fair, it's not actually a vulnerability considering the widget is in fact a "File Upload widget" only, and not necesarily an exclusive image upload widget.

If you take a look in [the documentation](https://github.com/trntv/yii2-file-kit#upload-widget), you can enforce client-side validation to accept only certain file types. If the user can pass the client-side validation, he will be able to upload files anyway because of how the widget works. You can check some more about validation in [here](https://github.com/trntv/yii2-file-kit#validation).

I thinks this is more related to how the widget is implemented rather than a Yii2-Starter-Kit issue.

**Comment by trntv** [comment]
every file type is allowed to be uploaded if it is not discarded by validation rules, but not every file should be interpreted by web server. I've changed nginx config to fix it. Thank you
