### ISSUE TITLE
Upload *.mp3 file problem

### ISSUE THREAD

**Issue by absentrv** [trntv/yii2-starter-kit#512]
When i upload *.mp3 file, nothing happens, has no  errors and $_FILES array is always empty.

```php
 echo $form->field($model, 'file')->widget(
            Upload::className(), [
        'url' => ['/file-storage/upload'],        
        'maxFileSize' => 10000000, // 10 MiB
    ]);
```

**Comment by hulyman** [comment]
@absentrv, show code near ActiveForm::begin.

**Comment by absentrv** [comment]
@hulyman ```php
<?php $form = ActiveForm::begin(); ?>
```

**Comment by ddinchev** [comment]
@absentrv your form does not allow multi-part form data. You won't be able to upload not only *.mp3 but any kind of files. Refer to the Yii2 guide:
http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html

You need to to create your form like this:
```
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
```

**Comment by absentrv** [comment]
@ddinchev sorry, i forgot say about Upload widget, i use trntv\filekit\widget\Upload.
Widget works(image, text file upload) without form enctype attribute.

**Comment by absentrv** [comment]
Someone can test downloading *.mp3 file via trntv\filekit\widget\Upload widget in own project?

**Comment by XzAeRo** [comment]
Using the Article section:
![fireshot capture 16 - update article_ test - http___backend yii2-starter-kit dev_article_update_id 1](https://cloud.githubusercontent.com/assets/1656037/22375111/90d297ba-e487-11e6-8e63-5e234c91b907.png)

In the article view:
![fireshot capture 17 - test - http___yii2-starter-kit dev_article_test](https://cloud.githubusercontent.com/assets/1656037/22375132/9eb1cd7e-e487-11e6-9c51-fee00232942d.png)

And each file is correctly downloaded.

I believe the problem is in your Model, or in the plugin configuration. Make sure you're allowing any file to be uploaded.

Also, I kindly suggest to replicate the `Article` and `ArticleAttachment` behavior. This is how you want to upload files to your application in a scalable way.

If you need more assistance, please provide information about your model, controller and view relevant sections.

**Comment by absentrv** [comment]
@XzAeRo I`m using standart (without modification) `Article` model/view/plugin configuration. `*.m3u` file correctly downloaded, but i need *.mp3* file downloading.

**Comment by XzAeRo** [comment]
![fireshot capture 18 - test - http___yii2-starter-kit dev_article_test](https://cloud.githubusercontent.com/assets/1656037/22375997/12fe51fe-e48b-11e6-9806-7aafdf84c04f.png)

I just uploaded that mp3 file, without a problem, and the download worked as expected.
If your file is not uploading, and if there's no application configuration issues, then the problem is your webserver configuration, because I don't think the problem is the file extension, is the file size.

Please check the [Nginx-PHP upload size limits](https://easyengine.io/tutorials/php/increase-file-upload-size-limit/), or [Apache-PHP upload size limit](https://www.cyberciti.biz/faq/linux-unix-apache-increase-php-upload-limit/).

Most of these webserver stacks come with a default 2MB max upload filesize (and most of the time, this widget doesn't catch this exact problem).

Don't hesitate to reply with more inquiries. Happy coding! :)

**Comment by absentrv** [comment]
Thank you so much, it works :) You are right, problem was in php.ini config file, `upload_max_filesize` limit.
